# Generated by Django 3.0 on 2020-05-03 15:15

import api.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Test',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=256)),
                ('lastName', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.upload_path)),
                ('link', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), null=True, size=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('city', models.CharField(max_length=256, null=True)),
                ('content', models.TextField(null=True)),
                ('area', models.CharField(max_length=20, null=True)),
                ('typeUser', models.CharField(max_length=256, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
