# Generated by Django 3.0 on 2020-05-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='rating',
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='email',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='experience',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='phone',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='vacancy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='workTime',
            field=models.TextField(null=True),
        ),
    ]
