# Generated by Django 3.0 on 2020-05-04 08:33

import api.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameNews', models.CharField(max_length=256, null=True)),
                ('content', models.TextField(null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path), null=True, size=3)),
                ('coordinate', models.CharField(max_length=256, null=True)),
                ('price', models.CharField(max_length=256, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
