# Generated by Django 3.0 on 2020-06-11 07:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='images',
            new_name='image1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='rating',
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='email',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='experience',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
        migrations.AddField(
            model_name='news',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
        migrations.AddField(
            model_name='news',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
        migrations.AddField(
            model_name='news',
            name='phone',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='vacancy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='workTime',
            field=models.TextField(null=True),
        ),
    ]
