# Generated by Django 3.0 on 2020-05-04 08:39

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200504_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
    ]
