# Generated by Django 3.0 on 2020-05-11 12:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200510_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='imageAvatar',
        ),
        migrations.AddField(
            model_name='news',
            name='imageFree',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
        migrations.AddField(
            model_name='news',
            name='imageOne',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
        migrations.AddField(
            model_name='news',
            name='imageTwo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
    ]
