# Generated by Django 3.0 on 2020-05-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200511_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='imageFree',
            new_name='imageThree',
        ),
    ]
