# Generated by Django 3.0 on 2020-05-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200511_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='imageAvatar',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='imageOne',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='imageThree',
            new_name='image3',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='imageTwo',
            new_name='image4',
        ),
    ]
