# Generated by Django 3.0 on 2020-05-04 09:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200504_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='participants',
        ),
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
