# Generated by Django 3.0 on 2020-05-04 12:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=api.models.Person),
        ),
    ]
