# Generated by Django 3.0 on 2020-05-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_news_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='avatar',
        ),
    ]
